services:
  api:
    image: aiogram/telegram-bot-api:latest
    restart: always
    environment:
      - TELEGRAM_API_ID="${TELEGRAM_API_ID}"
      - TELEGRAM_API_HASH="${TELEGRAM_API_HASH}"
      - TELEGRAM_LOCAL="${TELEGRAM_LOCAL}"
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    ports:
      - "8081:8081"
    networks:
      - insighter_worker_stage_new


  nginx:
    image: nginx:1.19-alpine
    restart: always
    depends_on:
      - api
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
      - ./nginx:/etc/nginx/conf.d/
    ports:
      - "80:80"
    networks:
      - insighter_worker_stage_new

volumes:
  telegram-bot-api-data:

networks:
  insighter_worker_stage_new:
    external: true